// Icons are provided by lucide-react (shadcn's default icon set). This façade
// keeps the existing Icon* names stable across the app, so every call site gets
// a clean, consistent icon from one place. lucide components accept width /
// height / className / style / strokeWidth just like the previous inline SVGs.
export {
  Database as IconDatabase,
  ArrowLeftRight as IconArrows,
  Layers as IconLayers,
  Bookmark as IconBookmark,
  Plus as IconPlus,
  Play as IconPlay,
  Download as IconDownload,
  Upload as IconUpload,
  Zap as IconBolt,
  Check as IconCheck,
  RefreshCw as IconRefresh,
  Trash2 as IconTrash,
  Pencil as IconEdit,
  Sun as IconSun,
  Moon as IconMoon,
  FlaskConical as IconFlask,
  Lock as IconLock,
  FileText as IconFile,
  Table2 as IconTable,
  Terminal as IconTerminal,
  Columns3 as IconColumns,
  Search as IconSearch,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  ArrowUpRight as IconArrowUpRight,
  Link2 as IconLink,
  X as IconClose,
  Save as IconSave,
  Settings as IconSettings,
  Activity as IconActivity,
  Bell as IconBell,
  HardDrive as IconHardDrive,
  Gauge as IconGauge,
  Rows3 as IconRows,
  TriangleAlert as IconWarning,
  Sparkles as IconSparkles,
  ListFilter as IconFilter,
  ChevronDown as IconChevronDown,
  Wrench as IconWrench,
  Copy as IconCopy,
  Star as IconStar,
  CircleCheck as IconCheckCircle,
  CircleAlert as IconAlert,
  Camera as IconCamera,
  Pause as IconPause,
  ChevronUp as IconChevronUp,
} from "lucide-react";
