"""Output sinks: where transformed rows go. The runner is agnostic — it hands
each batch to a sink. Choices: push to the target DB, or write a downloadable
SQL / CSV / JSON file."""
from __future__ import annotations

import csv
import io
import json
from abc import ABC, abstractmethod
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any, Optional

from .connectors.base import Connector


class Sink(ABC):
    #: True if writes hit an external database (affects reconciliation counts).
    is_db = False

    @abstractmethod
    def write_batch(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        """Consume one batch. Returns {"written", "skipped"}."""

    def finalize(self) -> None:
        pass

    def target_count(self) -> Optional[int]:
        return None


class DBSink(Sink):
    is_db = True

    def __init__(
        self,
        connector: Connector,
        schema: str,
        table: str,
        conflict_strategy: str,
        conflict_keys: list[str],
    ):
        self.c = connector
        self.schema = schema
        self.table = table
        self.conflict_strategy = conflict_strategy
        self.conflict_keys = conflict_keys

    def write_batch(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        return self.c.write_batch(
            self.schema, self.table, rows,
            conflict_strategy=self.conflict_strategy, conflict_keys=self.conflict_keys,
        )

    def target_count(self) -> Optional[int]:
        try:
            return self.c.count_rows(self.schema, self.table)
        except Exception:
            return None


def _sql_literal(v: Any) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float, Decimal)):
        return str(v)
    if isinstance(v, (datetime, date)):
        return "'" + v.isoformat() + "'"
    if isinstance(v, (bytes, bytearray)):
        return "'\\x" + bytes(v).hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


class FileSink(Sink):
    """Base for sinks that stream to a file on disk."""

    def __init__(self, path: str):
        self.path = path
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self._fh = open(path, "w", encoding="utf-8", newline="")
        self._count = 0

    def finalize(self) -> None:
        if not self._fh.closed:
            self._fh.close()

    def target_count(self) -> Optional[int]:
        return self._count


class SQLFileSink(FileSink):
    def __init__(
        self,
        path: str,
        table: str,
        columns: list[str],
        schema: str = "",
        include_ddl: bool = True,
        target_columns: Optional[list] = None,
    ):
        super().__init__(path)
        self.table = f"{schema}.{table}" if schema else table
        self.columns = columns
        self._fh.write(f"-- Generated by DB Migration Studio\n")
        if include_ddl and target_columns:
            self._fh.write(self._ddl(target_columns))
        self._collist = ", ".join(f'"{c}"' for c in columns)

    def _ddl(self, target_columns: list) -> str:
        defs = []
        for col in target_columns:
            if col.name not in self.columns:
                continue
            null = "" if col.nullable else " NOT NULL"
            defs.append(f'  "{col.name}" {col.data_type}{null}')
        if not defs:
            return ""
        return f'CREATE TABLE IF NOT EXISTS {self.table} (\n' + ",\n".join(defs) + "\n);\n\n"

    def write_batch(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        for r in rows:
            vals = ", ".join(_sql_literal(r.get(c)) for c in self.columns)
            self._fh.write(f"INSERT INTO {self.table} ({self._collist}) VALUES ({vals});\n")
        self._count += len(rows)
        return {"written": len(rows), "skipped": 0}


class CSVSink(FileSink):
    def __init__(self, path: str, columns: list[str]):
        super().__init__(path)
        self.columns = columns
        self._w = csv.DictWriter(self._fh, fieldnames=columns, extrasaction="ignore")
        self._w.writeheader()

    @staticmethod
    def _cell(v: Any) -> Any:
        if v is None:
            return ""
        if isinstance(v, (datetime, date)):
            return v.isoformat()
        return v

    def write_batch(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        for r in rows:
            self._w.writerow({c: self._cell(r.get(c)) for c in self.columns})
        self._count += len(rows)
        return {"written": len(rows), "skipped": 0}


class JSONSink(FileSink):
    """Streams a JSON array without buffering all rows in memory."""

    def __init__(self, path: str, columns: list[str]):
        super().__init__(path)
        self.columns = columns
        self._fh.write("[")
        self._first = True

    @staticmethod
    def _default(v: Any):
        if isinstance(v, (datetime, date)):
            return v.isoformat()
        if isinstance(v, Decimal):
            return float(v)
        if isinstance(v, (bytes, bytearray)):
            return bytes(v).hex()
        return str(v)

    def write_batch(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        for r in rows:
            obj = {c: r.get(c) for c in self.columns}
            sep = "" if self._first else ","
            self._first = False
            self._fh.write(sep + "\n  " + json.dumps(obj, default=self._default))
        self._count += len(rows)
        return {"written": len(rows), "skipped": 0}

    def finalize(self) -> None:
        if not self._fh.closed:
            self._fh.write("\n]\n")
        super().finalize()


EXPORT_EXT = {"sql": "sql", "csv": "csv", "json": "json"}
EXPORT_MEDIA = {
    "sql": "application/sql",
    "csv": "text/csv",
    "json": "application/json",
}
